### ISSUE TITLE
Error in case of using sorting

### ISSUE THREAD

**Issue by kubmichael** [papercliplabs/compound-v3-subgraph#2]
Hey, I am trying to use graph, I run following query:
```query MyQuery {
  absorbCollateralInteractions(
    orderDirection: desc
    orderBy: transaction__timestamp
  ) {
    market {
      id
    }
  }
}
```
And I face following error:
```{
  "errors": [
    {
      "message": "Failed to get entities from store: column cc.block_range does not exist, query = /* controller='filter',application='sgd636890',route='ba2ca1fe1ce74c4c-cbea7d8723cd41d3',action='18433315' */\nselect 'AbsorbCollateralInteraction' as entity, to_jsonb(c.*) as data from (select  c.*\n  from \"sgd636890\".\"absorb_collateral_interaction\" c left join \"sgd636890\".\"transaction\" as cc on (cc.\"id\" = c.\"transaction\" and cc.\"block_range\" @> $1) \n where c.block$ <= $2\n\n order by cc.\"timestamp\" desc, c.\"id\" desc\n limit 100) c -- binds: [18433315, 18433315]"
    }
  ]
}
```
Same issue was for others interactions, can  you please help

**Comment by spennyp** [comment]
Hey, this is an interesting find. After a bit of digging, it appears the graph node only supports nested entity sorting for `String` and `ID` types: [graph docs section](https://thegraph.com/docs/en/querying/graphql-api/#example-for-nested-entity-sorting)

![image](https://github.com/papercliplabs/compound-v3-subgraph/assets/31705429/99c0279b-f206-43e9-a044-d90a1be354df)

In this case, `timestamp` is a BigInt. I have asked the folks at the graph in [discord](https://discord.com/channels/438038660412342282/878269672921923635/1167144531179876472) to confirm, pending their response.

A potential work around would be to use transactions as the root of the query:
```graphql
{
    transactions(where: {absorbCollateralInteractions_not: []}, orderBy: timestamp, orderDir: desc}){
        id
        absorbCollateralInteractions {
          id
        }
    }
}
```

But, unfortunately since absorbCollateralInteractions is a derived entity, you cannot perform the `{absorbCollateralInteractions_not: []}` filter (again, limitation of the graph node).

Thus, without any changes in the schema or graph node, it seems it is not possible to perform such a query today. What we could do is add the `*InteractionCount` to the `Transaction` entity so you could instead do something like:
```graphql
{
    transactions(where: {absorbCollateralInteractionCount_gt: 0}, orderBy: timestamp, orderDir: desc){
        id
        absorbCollateralInteractions {
          id
        }
    }
}
```
The other benefit of start with` transactions` as the root is that you can see also all the corresponding `absorbDebtInteractions`, which allows you to assemble the entire picture of the liquidation.

Let me know if adding `*InteractionCount` would be a suitable solve for you and I can implement this.

**Comment by spennyp** [comment]
The change outlined above has been [implemented](https://github.com/papercliplabs/compound-v3-subgraph/commit/80dbe3582c65535be8df268706e743a2a40f77a0#diff-efc1675187620595b0844197a25c35eac9b6df752f9182e5cffddee6f27a8489R717-R726) on the `Transaction` entity and deployed:

![Screenshot 2023-10-31 at 15 22 47](https://github.com/papercliplabs/compound-v3-subgraph/assets/31705429/1f27e7c8-87cb-4dfd-9685-e386309ec86e)



You can now use a query like this to achieve what you want:
```graphql
{
    transactions(where: {absorbCollateralInteractionCount_gt: 0}, orderBy: timestamp, orderDirection: desc){
        hash
        timestamp
        absorbCollateralInteractions {
            amount
        }
    }
}
```


Let me know if there are any other questions!
Closing this issue 👍
